version: '3'

services:
  app:
    container_name: lottery
    image: python:latest
    ports:
      - 8000:8000
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'pip3 install -r requirements.txt && python3 lottery/manage.py makemigrations && python3 lottery/manage.py migrate && python3 lottery/manage.py runserver 0.0.0.0:8000'